server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
    context-path: /autochess

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autochess?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456MyMysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath://templates/
    suffix: .html
    enabled: true
    encoding: UTF-8
    cache: false

mybatis:
  type-aliases-package: com.galaxyinblue.autochess.entity
  mapper-locations: classpath:/mapper/*.xml
